spring:
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user/**
        filters:
        - RewritePath=/user/(?<path>.*), /$\{path}
        - name: CircuitBreaker
          args:
            name: cloudCircuitBreaker
            fallbackUri: forward:/fallback
      - id: auth-server
        uri: lb://AUTH-SERVER
        predicates:
        - Path=/auth/**   
        filters:
        - RewritePath=/auth/(?<path>.*), /$\{path}
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**   
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs  
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET     
            - POST
            - PUT
            - DELETE
            - OPTIONS
            allowed-headers:
              - authorization
              - content-type
              - xsrf-token
  application:
    name: gateway
  
      
eureka:
  client:
    service-url:
      defaultZone: http://admin:nimda@myserver:8082/eureka/
    register-with-eureka: true        
  instance:
    prefer-ip-address: false
    hostname: myserver
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    

server:
  port: 1443
 
gateway:
  clientId: cloud
  clientSecret: cloud
  resourceId: gateway

resilience4j.circuitbreaker:
    configs:
        default:
            slidingWindowSize: 100
            slidingWindowType: COUNT_BASED
            permittedNumberOfCallsInHalfOpenState: 10
            waitDurationInOpenState: 60000
            failureRateThreshold: 50
            registerHealthIndicator: true
            ignoreExceptions:
                - com.jedlab.framework.exceptions.ServiceException
    instances:
        cloudCircuitBreaker:
            baseConfig: default 

